### ISSUE TITLE
PA Review: User Profile

### ISSUE THREAD

**Issue by mkochalko** [mkochalko/southweast#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by samwalker191** [comment]
Looks good! Please see my recommendations below:

![image](https://user-images.githubusercontent.com/49164119/72458001-9dbb6d80-377c-11ea-81a7-59c4ba363bf6.png)

---

![image](https://user-images.githubusercontent.com/49164119/72458007-a0b65e00-377c-11ea-8f5d-a3947f17020a.png)

---

![image](https://user-images.githubusercontent.com/49164119/72458015-a613a880-377c-11ea-8a7c-3ce43bfc93b6.png)

---

![image](https://user-images.githubusercontent.com/49164119/72458022-a9a72f80-377c-11ea-9d21-0870bdc115d0.png)

---

![image](https://user-images.githubusercontent.com/49164119/72458029-add34d00-377c-11ea-9a9b-a6cca118f204.png)

---

![image](https://user-images.githubusercontent.com/49164119/72458045-b3309780-377c-11ea-986f-caea21b28d5b.png)

**Comment by mkochalko** [comment]
Completed most of these comments, the couple that i did not finish I will come back to once i have my bookings and create flights/trips complete. These items include: 
* Edit user profile page
* Create actual unique flight confirmation codes
* Fix my dates and times to accurately reflex the correct date (I will end up pulling this info straight from API response.
